name: Create Release

on:
  workflow_dispatch:
    inputs:
        tag_name:
          description: 'Version tag v*'
          required: true
          type: string
        release_name: 
          description: 'Release name'
          required: true
          type: string
        summary:
          description: 'Release summary'
          required: true
          type: string

jobs:
  build:
    permissions: write-all
    name: Build UnityPackage
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      # Cache
      - name: Cache
        uses: actions/cache@v4
        with:
          path: Library
          key: Library
          restore-keys: Library-

      # Build
      - name: Build .unitypackage
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: WebGL
          buildMethod: ExportUnityPackage.ExportAllAssets # Path to the export method containing the namespace.

      # Upload
      - name: Upload .unitypackage
        uses: actions/upload-artifact@v4
        with:
          name: playgama-bridge
          path: Build

      # Add tag name
      - name: Rename file 
        run: mv Build/package/playgama-bridge.unitypackage Build/package/playgama-bridge-${{inputs.tag_name}}.unitypackage

      # Release
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ inputs.tag_name }}
          name: ${{ inputs.release_name }}
          body: ${{inputs.summary}}
          files: Build/package/playgama-bridge.unitypackage
          
