name: Create Release

on:
  workflow_dispatch:
    inputs:
        tag_name:
          description: 'Version tag v*'
          required: true
          type: string
        release_name: 
          description: 'Release name'
          required: true
          type: string
        summary:
          description: 'Release summary'
          required: true
          type: string

jobs:
  build:
    permissions: write-all
    name: Build UnityPackage
    runs-on: ubuntu-latest
    steps:
      # Checkout bridge-unity
      - name: Checkout bridge-unity
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: New branch
        run: |
          git checkout -b build-branch

      # Checkout bridge by version
      - name: Checkout bridge by version
        uses: actions/checkout@v4
        with:
          repository: lysoff/bridge
          ref: ${{ inputs.tag_name }}
          path: bridge/
          token: ${{ secrets.TRIGGER_REPO_TOKEN }}

      # Build bridge
      - name: Build bridge
        run: | 
          cd bridge
          npm i 
          npm run build
          data=$(sed -n '2p' "dist/playgama-bridge.js")
          echo "$data" > "dist/playgama-bridge.js"

      # Inject script
      - name: Inject script
        run: |
          mv bridge/dist/playgama-bridge.js Assets/WebGLTemplates/Bridge/playgama-bridge.js
          rm -rf bridge
          html_file="Assets/WebGLTemplates/Bridge/index.html"
          replacement='<script src=".\/script.js" \/>'
          sed -i '' '/<!-- #cdn -->/,/<!-- #endcdn -->/c\<script src="./playgama-bridge.js"></script>' Assets/WebGLTemplates/Bridge/index.html

      # Upload html and script
      - name: Upload  html and script
        uses: actions/upload-artifact@v3
        with:
          name: html and script
          path: |
            Assets/WebGLTemplates/Bridge/playgama-bridge.js
            Assets/WebGLTemplates/Bridge/index.html

      - name: Commit-changes
        run: |
          git add .
          git config --global user.email "services@playgama.com"
          git config --global user.name "Playgama"
          git commit -m 'build changes'

      # Cache
      - name: Cache
        uses: actions/cache@v4
        with:
          path: Library
          key: Library
          restore-keys: Library-

      # Build
      - name: Build .unitypackage
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: WebGL
          buildMethod: ExportUnityPackage.ExportAllAssets # Path to the export method containing the namespace.

      # Upload
      - name: Upload .unitypackage
        uses: actions/upload-artifact@v4
        with:
          name: playgama-bridge
          path: Build

      # Add tag name
      - name: Rename file 
        run: sudo mv Build/package/playgama_bridge.unitypackage Build/package/playgama_bridge_${{inputs.tag_name}}.unitypackage

      # Release
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ inputs.tag_name }}
          name: ${{ inputs.release_name }}
          body: ${{inputs.summary}}
          files: Build/package/playgama_bridge_${{inputs.tag_name}}.unitypackage
      
