name: Export Unity Package

on:
  workflow_dispatch:
    inputs:
      exportPath:
        description: "Path to the folder in Unity project to export (relative to Assets/)"
        required: true
        default: "."

jobs:
  export-package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Build
      - name: Build .unitypackage
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: WebGL
          buildMethod: ExportUnityPackage.ExportAllAssets # Path to the export method containing the namespace.

      # Upload
      - name: Upload .unitypackage
        uses: actions/upload-artifact@v4
        with:
          name: Unity Package
          path: /build/playgama-bridge.unitypackage
          
