name: Export Package

on:
  workflow_dispatch:
    inputs:
        tagname:
          description: 'Version tag v*'
          required: true
          type: string
        release_name: 
          description: 'Release name'
          required: true
          type: string
        summary:
          description: 'Release summary'
          required: true
          type: string

jobs:
  build:
    name: Build UnityPackage
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      # Cache
      - name: Cache
        uses: actions/cache@v4
        with:
          path: Library
          key: Library
          restore-keys: Library-

      # Build
      - name: Build .unitypackage
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: WebGL
          buildMethod: ExportUnityPackage.ExportAllAssets # Path to the export method containing the namespace.

      # Upload
      - name: Upload .unitypackage
        uses: actions/upload-artifact@v4
        with:
          name: playgama-bridge
          path: Build

          
      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ inputs.tagname }}
          release_name: Release ${{ inputs.release_name }}
          body: ${{inputs.summary}}
          draft: false
          prerelease: false
