name: Export Unity Package

on:
  workflow_dispatch:
    inputs:
      exportPath:
        description: "Path to the folder in Unity project to export (relative to Assets/)"
        required: true
        default: "."

jobs:
  export-package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          buildMethod: ExportUnityPackage.ExportAllAssets
          targetPlatform: WebGL
     
      - name: Upload Unity package
        uses: actions/upload-artifact@v3
        with:
          name: exported-unity-package
          path: playgama-bridge.unitypackage
