name: Main

on: 
  workflow_dispatch:
     inputs:
        tag_name:
          description: 'Version tag v*'
          required: true
          type: string
        release_name: 
          description: 'Release name'
          required: true
          type: string
        summary:
          description: 'Release summary'
          required: true
          type: string

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: echo ${{ github.sha }} > Release.txt
      - name: Test
        run: cat Release.txt
      - name: Trigger workflow
        env:
          GITHUB_TOKEN: ${{ secrets.TRIGGER_REPO_TOKEN }}
        run: |
            curl -X POST \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer $GITHUB_TOKEN" \
              https://api.github.com/repos/lysoff/bridge-construct/actions/workflows/release.yml/dispatches \
              -d '{"ref":"main", "inputs": { "tag_name": "${{ inputs.tag_name }}", "release_name": "${{ inputs.release_name }}", "summary": "${{ inputs.summary }}" }}'
        
      # - name: Release
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.TRIGGER_REPO_TOKEN }}
      #   uses: softprops/action-gh-release@v2
      #   with:
      #     repository: lysoff/bridge-construct
      #     tag_name: v3.0.0
      #     files: Release.txt
